### PR TITLE
added institution but unable to login as institution

### PR DESCRIPTION
**Pull request by kellysoh**

### CODE REVIEW

**Comment by kellysoh** [comment]
@ischenkel Plz approve this pull request

**Comment by judydhayoung** [comment]
Isaac, have you tried changing your user role to institution before testing? I changed mine in the database and it seemed fine.

I also has the same thought about copying consumer and making minor changes, but I wonder how we can pass down the institution role or show different things for consumer and institution role in the bloc...

________________________________

**Comment by ischenkel** [comment]
I did change my role to institution. The Donation button on the main page routes fine but the Donation button in the side bar routes to a regular donation form with  + and - button instead of quantity input

**Comment by kellysoh** [comment]
Okay. So the 

- [ ] Change drawer to navigate to the institution page 

- [ ] Combine Institution and Consumer page together and add if statement to display the different features depending on the role

**Comment by ischenkel** [comment]
> Okay. So the
> 
> * [x]  Change drawer to navigate to the institution page
> * [ ]  Combine Institution and Consumer page together and add if statement to display the different features depending on the role

yes for the first one.
for the second one, I was just wondering about the decision, not requesting change. I think there're benefits of doing it this way as to make future changes to the institution role UI on these screens more maintainable. The trade-off is that the app size would be enlarged, but that's not a big concern atm.

**Comment by kellysoh** [comment]
@ischenkel @judydhayoung  Updated the drawer and changed the color of buttons in the dashboard!:)

**Pull request merged**
