### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by StevePrat**
Translated pages for consumer & supplier. Church admin page is not translated yet.

### CODE REVIEW

**Comment by StevePrat** [comment]
Translated pages for consumer, supplier, and institution. Church admin page is not translated yet.

**Comment by StevePrat** [comment]
Hi Kelly, thanks for testing more thoroughly than I did haha. I have managed to fix the "fulfill this request" error, but I noticed there's something not translated yet on that page also. I'll need some more time to translate those parts that I overlooked (including the categories). Thanks.

**Comment by StevePrat** [comment]
image

On mine the categories are already translated

**Comment by StevePrat** [comment]
Hi @kellysoh the 2 problems you showed earlier should have been resolved, please help to check. @yosiassapari Pascal you can help to check too if you have time :) .

**Comment by kellysoh** [comment]
It looks great Steven! I think you can merge the branch to develop!

**Pull request merged**
