### PR TITLE
changed labels and colors of dashboard buttons

### PR DESCRIPTION
**Pull request by kellysoh**

### CODE REVIEW

**Comment by judydhayoung** [comment]
also... would the dashboard look different for institution role (bc they can be supplier and consumer at the same time right) ?

**Comment by kellysoh** [comment]
@judydhayoung @ischenkel In today's meeting, we have decided to change some of the labels again. Please check out the labels and changed colors (we decided to choose the colors from the logo). For the header, I think it's better to have the header in the future, but for now, we agreed just changing labels and colors would be enough. Thanks.

**Comment by kellysoh** [comment]
@judydhayoung Plz approve this pull request

**Comment by judydhayoung** [comment]
merged

**Pull request merged**
